#Description: Mastermind is a game where the computer chooses colors 
#at random, where any color can be chosen more than once, out of six.
#The goal of the user is to guess the colors generated by the computer
#within 10 attempts. If the user guesses all four colors correctly in
#the correct positions within 10 attempts then they win the game. If 
#the user loses, then the computer tells the user the correct colors 
#and their correct positions.  

import random

#all the colors in mastermind
colors = ["blue", "black", "green", "yellow", "white", "red"]

#the computer generated random values
c1 = random.choice(colors)
c2 = random.choice(colors)
c3 = random.choice(colors)
c4 = random.choice(colors)

i = 0 #this is for the while loop

#while loop begins
while i < 10:
    
    print("\nYou have " + str(10 - i) + " attempt(s) left\n")
    
    #reset the counter for the perfect, close, and no 
    perfect = 0
    close = 0
    no = 0
    
    #take in user guesses and make sure it is the right case
    info1 = input("Please enter your guess for the first color: ").lower()
    info2 = input("Please enter your guess for the second color: ").lower()
    info3 = input("Please enter your guess for the third color: ").lower()
    info4 = input("Please enter your guess for the fourth color: ").lower()

    if((info1 == c1) and (info2 == c2) and (info3 == c3) and (info4 == c4)):
        print("YOU WON!")
        break
    
    #check how many are perfect or close or no
    if(c1 == info1):
        perfect+=1
    elif((c1 == info2) or (c1 == info3)  or (c1 == info4)):
        close+=1
    else:
        no+=1

    if(c2 == info2):
        perfect+=1
    elif((c2 == info1) or (c2 == info3)  or (c2 == info4)):
        close+=1
    else:
        no+=1

    if(c3 == info3):
        perfect+=1
    elif((c3 == info2) or (c3 == info1)  or (c3 == info4)):
        close+=1
    else:
        no+=1

    if(c4 == info4):
        perfect+=1
    elif((c4 == info2) or (c4 == info3)  or (c4 == info1)):
        close+=1
    else:
        no+=1
    
    print("\nPerfect guesses: " + str(perfect) + "\nClose guesses: " + str(close)
		+ "\nIncorrect guesses: " + str(no));
    i+=1
#while loop ends

#check if the user has lost
if (i == 10):
    print("Sorry, you lost! Here are the correct numbers in the correct order: \n"  
           + c1 + '\n' + c2 + '\n' + c3 + '\n' + c4)
#end of if 